# Basic Information 
title: Daniel Sungho Jung
position: Ph.D. Candidate
affiliation: Seoul National University
affiliation_link: https://www.snu.ac.kr/
email: dqj5182@snu.ac.kr

# Search Engine Optimization (SEO)
keywords: Daniel Sungho Jung, Daniel Jung, Sungho Jung
canonical: https://dqj5182.github.io/
description: Daniel Sungho Jung is a Ph.D. candiate at Seoul National University. His research lies in 3D human mesh reconstruction and 3D scene reconstruction.

# Links
google_scholar: https://scholar.google.com/
cv_link: https://drive.google.com/file/d/1yTjZTre2c9AXqBld60ZsYsO5LCMZpirQ/view?usp=sharing
github_link: https://github.com/dqj5182
linkedin: https://www.linkedin.com/in/danieljung0121/
twitter: https://twitter.com/dqj5182

# Images 
avatar: ./assets/img/profile.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
